using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SFGraphics.GLObjects
{
    /// <summary>
    /// 
    /// </summary>
    public interface IGLObject
    {
        // TODO: All shaders and textures should inherit from this.
        // Provide an interface for memory management.

        /// <summary>
        /// The value generated by GL.Gen() for a texture, buffer, etc. Do not attempt to bind this when the object has gone out of scope.
        /// </summary>
        int Id { get; }
    }
}
