using System;
using System.IO;
using System.Collections.Generic;
using OpenTK;
using OpenTK.Graphics.OpenGL;
using System.Text;

namespace SFGraphics.GLObjects.Shaders
{
    /// <summary>
    /// Encapsulates a shader program and attached shaders. Errors are stored to an internal log, which can be exported. Check if the shader was created successfully before rendering!
    /// </summary>
	public class Shader : IGLObject
	{
        /// <summary>
        /// The ID generated by GL.CreateProgram().
        /// </summary>
		public int Id { get; }

        /// <summary>
        /// True when the link status is ok and all attached shaders compiled.
        /// If false, rendering with this shader will most likely cause a crash.
        /// </summary>
        private bool programStatusIsOk = true;

        private int vertShaderId;
        private int fragShaderId;

        private bool hasGeometryShader = false;
        private int geomShaderId;

        private bool hasCheckedProgramCreation = false;
        /// <summary>
        /// True when the program and shader compilation have been checked for errors.
        /// </summary>
        public bool HasCheckedCompilation { get { return hasCheckedProgramCreation; } }

        private ShaderLog errorLog = new ShaderLog();

        // Vertex Attributes and Uniforms
        int activeUniformCount = 0;
        int activeAttributeCount = 0;
		private Dictionary<string, int> vertexAttributeAndUniformLocations = new Dictionary<string, int>();

        // Write these names to the error log later rather than throwing an exception.
        private HashSet<string> invalidUniformNames = new HashSet<string>();

        /// <summary>
        /// Initializes the programID. Attach and compile shaders with LoadShader() before using.
        /// </summary>
        public Shader()
        {
            Id = GL.CreateProgram();
            errorLog.AppendHardwareAndVersionInfo();
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetFloat(string uniformName, float value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform1(GetVertexAttributeUniformLocation(uniformName), value);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetInt(string uniformName, int value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform1(GetVertexAttributeUniformLocation(uniformName), value);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetUint(string uniformName, uint value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform1(GetVertexAttributeUniformLocation(uniformName), value);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform. True = 1. False = 0.</param>
        public void SetBoolToInt(string uniformName, bool value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            // if/else is faster than the ternary operator. 
            if (value)
                GL.Uniform1(GetVertexAttributeUniformLocation(uniformName), 1);
            else
                GL.Uniform1(GetVertexAttributeUniformLocation(uniformName), 0);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetVector3(string uniformName, Vector3 value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform3(GetVertexAttributeUniformLocation(uniformName), value);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetVector3(string uniformName, float x, float y, float z)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform3(GetVertexAttributeUniformLocation(uniformName), x, y, z);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetVector4(string uniformName, Vector4 value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform4(GetVertexAttributeUniformLocation(uniformName), value);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetVector4(string uniformName, float x, float y, float z, float w)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.Uniform4(GetVertexAttributeUniformLocation(uniformName), x, y, z, w);
        }

        /// <summary>
        /// Names not present in the shader are ignored and saved to the error log.
        /// </summary>
        /// <param name="uniformName">The uniform variable name</param>
        /// <param name="value">The value to assign to the uniform</param>
        public void SetMatrix4x4(string uniformName, ref Matrix4 value)
        {
            if (!vertexAttributeAndUniformLocations.ContainsKey(uniformName) && !invalidUniformNames.Contains(uniformName))
            {
                invalidUniformNames.Add(uniformName);
                return;
            }

            GL.UniformMatrix4(GetVertexAttributeUniformLocation(uniformName), false, ref value);
        }

        /// <summary>
        /// Gets the index of the vertex attribute or uniform variable. Returns -1 if not found.
        /// </summary>
        /// <param name="name">The name of the vertex attribute or uniform</param>
        /// <returns>The index of the attribute/uniform or -1 if not found </returns>
        public int GetVertexAttributeUniformLocation(string name)
        {
			int value;
            if (vertexAttributeAndUniformLocations.TryGetValue(name, out value))
            {
                return value;
            }
            else
                return -1;
		}

        /// <summary>
        /// Enables the vertex attribute arrays for all active attributes.
        /// Ensures that extra attributes aren't enabled, which causes crashes on Geforce drivers.
        /// </summary>
        public void EnableVertexAttributes()
        {
            // Only enable the necessary vertex attributes.
            // Enabling extra vertex attributes crashes on Nvidia.
            for (int location = 0; location < activeAttributeCount; location++)
			{
                GL.EnableVertexAttribArray(location);
			}
		}

        /// <summary>
        /// Disables the vertex attribute arrays for all active attributes.
        /// Ensures that extra attributes aren't enabled, which causes crashes on Geforce drivers.
        /// </summary>
        public void DisableVertexAttributes()
        {
            // Disable all the vertex attributes. This could be used with a VAO in the future.
            for (int location = 0; location < activeAttributeCount; location++)
			{
				GL.DisableVertexAttribArray(location);
			}
		}

        /// <summary>
        /// Gets the error log containing hardware info, version number, compilation/linker errors, and attempts to initialize invalid uniform or vertex attribute names.
        /// </summary>
        /// <returns></returns>
        public string GetErrorLog()
        {
            // Don't append program errors until all the shaders are attached and compiled.
            errorLog.AppendProgramInfoLog(Id);

            // Collect all of the spelling mistakes.
            errorLog.AppendUniformNameErrors(invalidUniformNames);

            return errorLog.ToString();
        }

		private void AddVertexAttribute(string name)
        {
            if (vertexAttributeAndUniformLocations.ContainsKey(name))
                vertexAttributeAndUniformLocations.Remove(name);
			int position = GL.GetAttribLocation(Id, name);
            vertexAttributeAndUniformLocations.Add(name, position);
        }

        private void AddUniform(string name)
        {
            if (vertexAttributeAndUniformLocations.ContainsKey(name))
                vertexAttributeAndUniformLocations.Remove(name);
            int position = GL.GetUniformLocation(Id, name);
            vertexAttributeAndUniformLocations.Add(name, position);
        }

        private void LoadUniforms()
        {
            GL.GetProgram(Id, GetProgramParameterName.ActiveUniforms, out activeUniformCount);
            //errorLog.AppendLine("Uniform Count: " + activeUniformCount);

            for (int i = 0; i < activeUniformCount; i++)
            {
                // Ignore invalid uniforms. 0 is "None" for type.
                ActiveUniformType uniformType;
                int uniformSize;
                string uniform = GL.GetActiveUniform(Id, i, out uniformSize, out uniformType);
                if (uniformType != 0)
                {
                    uniform = RemoveEndingBrackets(uniform);
                    AddUniform(uniform);
                }
            }
        }

        private void LoadAttributes()
        {
            GL.GetProgram(Id, GetProgramParameterName.ActiveAttributes, out activeAttributeCount);
            //errorLog.AppendLine("Attribute Count: " + activeAttributeCount);

            for (int i = 0; i < activeAttributeCount; i++)
            {
                // Ignore invalid attributes.
                ActiveAttribType attributeType;
                int attributeSize;
                string attribute = GL.GetActiveAttrib(Id, i, out attributeSize, out attributeType);
                if (attributeType != ActiveAttribType.None)
                {
                    attribute = RemoveEndingBrackets(attribute);
                    AddVertexAttribute(attribute);
                }
            }
        }

        private static string RemoveEndingBrackets(string name)
        {
            // Removes the brackets at the end of the name.
            // Ex: "name[0]" becomes "name".
            int index = name.IndexOf('[');
            if (index > 0)
                name = name.Substring(0, index);
            return name;
        }

        /// <summary>
        /// Reads the specified text file and attempts to compile and attach the shader. 
        /// Supported shader types are fragment (.frag), vertex (.vert), and geometry (.geom).
        /// </summary>
        /// <param name="filePath">The path to a shader text file. The loaded shader type is based on the file extension.</param>
        public void LoadShader(string filePath)
        {
            // Compile and attach before linking.
            LoadShaderBasedOnType(filePath);
            GL.LinkProgram(Id);

            LoadAttributes();
            LoadUniforms();
        }

        private void LoadShaderBasedOnType(string filePath)
        {
            if (filePath.EndsWith(".frag"))
            {
                AttachAndCompileShader(filePath, ShaderType.FragmentShader, Id, out fragShaderId);
            }
            else if (filePath.EndsWith(".vert"))
            {
                AttachAndCompileShader(filePath, ShaderType.VertexShader, Id, out vertShaderId);
            }
            else if (filePath.EndsWith(".geom"))
            {
                AttachAndCompileShader(filePath, ShaderType.GeometryShader, Id, out geomShaderId);
                hasGeometryShader = true;
            }
            else
            {
                throw new NotSupportedException(filePath + " does not have a suppported shader type extension.");
            }
        }

        private void AttachAndCompileShader(string shaderFile, ShaderType type, int program, out int id)
        {
            string shaderText = File.ReadAllText(shaderFile);
            id = GL.CreateShader(type);

            GL.ShaderSource(id, shaderText);
            GL.CompileShader(id);
            GL.AttachShader(program, id);

            // Get the name of the shader. 
            string[] parts = shaderFile.Split('\\');
            string shaderName = parts[parts.Length - 1];
            errorLog.AppendShaderInfoLog(shaderName, id, type);
        }

        public bool ProgramCreatedSuccessfully()
        {
            // Should be checked before rendering. 
            // Rendering when this returns false will almost always result in a crash.
            if (!hasCheckedProgramCreation)
                programStatusIsOk = CheckProgramStatus();
            return programStatusIsOk;
        }

        private bool CheckProgramStatus()
        {
            // This is checked frequently, so only do it once.
            hasCheckedProgramCreation = true;

            // Check for linker errors first. 
            int linkStatus = 1;
            GL.GetProgram(Id, GetProgramParameterName.LinkStatus, out linkStatus);
            if (linkStatus == 0)
                return false;

            // Make sure the shaders were compiled correctly.
            int compileStatusVS = 1;
            GL.GetShader(vertShaderId, ShaderParameter.CompileStatus, out compileStatusVS);

            int compileStatusFS = 1;
            GL.GetShader(fragShaderId, ShaderParameter.CompileStatus, out compileStatusFS);

            // Most shaders won't use a geometry shader.
            int compileStatusGS = 1;
            if (hasGeometryShader)
                GL.GetShader(geomShaderId, ShaderParameter.CompileStatus, out compileStatusGS);

            // The program was linked, but the shaders may have minor syntax errors.
            return (compileStatusFS != 0 && compileStatusVS != 0 && compileStatusGS != 0);
        }
	}
}

