using OpenTK.Graphics.OpenGL;

namespace SFGraphics.GLObjects
{
    /// <summary>
    /// Encapsulates an OpenGL vertex array object.
    /// </summary>
    public class VertexArrayObject : IGLObject
    {
        /// <summary>
        /// The value generated by GL.GenVertexArray(). 
        /// Do not attempt to bind <see cref="Id"/> when the object has become unreachable.
        /// </summary>
        public int Id { get; }

        /// <summary>
        /// Creates an empty vertex array object.
        /// The vertex array object must first be bound with <see cref="Bind"/>.
        /// </summary>
        public VertexArrayObject()
        {
            Id = GL.GenVertexArray();
        }

        /// <summary>
        /// Binds the vertex array <see cref="Id"/>.
        /// </summary>
        public void Bind()
        {
            GL.BindVertexArray(Id);
        }

        /// <summary>
        /// Binds the default vertex array value of 0.
        /// </summary>
        public void Unbind()
        {
            GL.BindVertexArray(0);
        }
    }
}
